# Generated by Django 6.1.1 on 2026-09-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SampleUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sector_samples/')),
                ('image_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_uis', to='sectors.sector')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LayoutGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_system', models.CharField(blank=True, max_length=200)),
                ('max_content_width', models.CharField(blank=True, max_length=100)),
                ('spacing_system', models.CharField(blank=True, max_length=200)),
                ('border_radius', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout_guideline', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Layout Guideline',
                'verbose_name_plural': 'Layout Guidelines',
            },
        ),
        migrations.CreateModel(
            name='ImageryGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guideline_type', models.CharField(choices=[('recommended', 'Recommended'), ('avoid', 'Avoid')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagery_guidelines', to='sectors.sector')),
            ],
            options={
                'ordering': ['guideline_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=20)),
                ('secondary', models.CharField(max_length=20)),
                ('accent', models.CharField(max_length=20)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_palette', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
            },
        ),
        migrations.CreateModel(
            name='AccessibilityGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('standard', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_guidelines', to='sectors.sector')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ShapeGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=100)),
                ('border_radius', models.CharField(blank=True, max_length=100)),
                ('border_style', models.CharField(blank=True, max_length=100)),
                ('shadow_style', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shape_guideline', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Shape Guideline',
                'verbose_name_plural': 'Shape Guidelines',
            },
        ),
        migrations.CreateModel(
            name='TypographyGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_font', models.CharField(max_length=100)),
                ('secondary_font', models.CharField(blank=True, max_length=100)),
                ('heading_weight', models.CharField(blank=True, max_length=50)),
                ('body_weight', models.CharField(blank=True, max_length=50)),
                ('heading_scale', models.CharField(blank=True, max_length=100)),
                ('line_height', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='typography_guideline', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Typography Guideline',
                'verbose_name_plural': 'Typography Guidelines',
            },
        ),
        migrations.CreateModel(
            name='PersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality_profiles', to='sectors.sector')),
            ],
            options={
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('sector', 'name'), name='unique_sector_personality')],
            },
        ),
        migrations.CreateModel(
            name='ComponentGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('usage_guideline', models.TextField(blank=True)),
                ('do_use', models.TextField(blank=True)),
                ('avoid', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_guidelines', to='sectors.sector')),
            ],
            options={
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('sector', 'component_name'), name='unique_sector_component')],
            },
        ),
        migrations.CreateModel(
            name='SectorCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='sectors.sector')),
            ],
            options={
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('sector', 'name'), name='unique_sector_characteristic')],
            },
        ),
    ]
